name: auto_gpt_flutter_client
description: A Flutter project for AutoGPT.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.2
  flutter_highlight: ^0.7.1
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  http: ^0.13.6
  shared_preferences: ^2.2.2
  graphview: ^1.3.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.3
  firebase_analytics: ^10.5.1
  google_sign_in: ^6.1.6
  uuid: ^4.0.0
  url_launcher: ^6.1.15
  fluttertoast: ^8.2.3
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

funding:
  github: https://github.com/sponsors/infinitered

readme: |
  # AutoGPT Flutter Client

  A Flutter project for AutoGPT.

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

  assets:
    - assets/tree_structure.json
    - assets/images/google_logo.svg.png
    - assets/images/github_logo.svg.png
    - assets/images/autogpt_logo.png
    - assets/images/discord_logo.png
    - assets/images/twitter_logo.png
    - assets/general_tree_structure.json
    - assets/coding_tree_structure.json
    - assets/data_tree_structure.json
    - assets/scrape_synthesize_tree_structure.json
