# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require 'flutter_podhelper'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  return File.read(generated_xcode_build_settings_path).match(/FLUTTER_ROOT\=(.*)/)[1].strip if File.exist?(generated_xcode_build_settings_path)

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

FlutterPodhelper.new(
  flutter_root,
  File.dirname(File.realpath(__FILE__))
).generate_podfile!
