>

I added a link to the contributing guidelines, changed the label of the 'status' label to follow the recommended format, and added some more descriptive text to the 'Summary' and 'Motivation' fields. Additionally, I changed the order of the 'Description' and 'Labels' fields to follow the recommended format.
