title: AutoGPT Documentation
base_url: https://docs.agpt.co/
repo_url: https://github.com/Significant-Gravitas/AutoGPT
docs_dir: content
relative_links: true

nav:
  - text: Home
    link: index.md

  - text: AutoGPT Agent
    children:
      - text: Introduction
        link: AutoGPT/index.md
      - text: Setup
        children:
          - text: Setting up AutoGPT
            link: AutoGPT/setup/index.md
          - text: Set up with Docker
            link: AutoGPT/setup/docker.md
      - text: Usage
        link: AutoGPT/usage.md
      - text: Plugins
        link: AutoGPT/plugins.md
      - text: Help us improve AutoGPT
        children:
          - text: Share your debug logs with us
            link: AutoGPT/share-your-logs.md
          - text: Contribution guide
            link: contributing.md
          - text: Running tests
            link: AutoGPT/testing.md
          - text: Code of Conduct
            link: code-of-conduct.md

  - text: Benchmark
    link: https://github.com/Significant-Gravitas/AutoGPT/blob/master/benchmark/README.md

  - text: Forge
    children:
      - text: Introduction
        link: forge/get-started.md

  - text: Frontend
    link: https://github.com/Significant-Gravitas/AutoGPT/blob/master/frontend/README.md

  # - text: Challenges
  #   children:
  #     - text: Introduction
  #       link: challenges/introduction.md
  #     - text: List of Challenges
  #       children:
  #         - text: Memory
  #           children:
  #             - text: Introduction
  #               link: challenges/memory/introduction.md
  #             - text: Memory Challenge A
  #               link: challenges/memory/challenge_a.md
  #             - text: Memory Challenge B
  #               link: challenges/memory/challenge_b.md
  #             - text: Memory Challenge C
  #               link: challenges/memory/challenge_c.md
  #             - text: Memory Challenge D
  #               link: challenges/memory/challenge_d.md
  #         - text: Information retrieval
  #           children:
  #             - text: Introduction
  #               link: challenges/information_retrieval/introduction.md
  #             - text: Information Retrieval Challenge A
  #               link: challenges/information_retrieval/challenge_a.md
  #             - text: Information Retrieval Challenge B
  #               link: challenges/information_retrieval/challenge_b.md
  # - text: Submit a Challenge
  #   link: challenges/submit.md
  # - text: Beat a Challenge
  #   link: challenges/beat.md

  - text: License
    link: https://github.com/Significant-Gravitas/AutoGPT/blob/master/LICENSE

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book-open-variant
  favicon: favicon.png
  features:
    - navigation.sections
    - toc.follow
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

highlight_theme: monokai
mathjax_config:
  tex:
    inlineMath: [['$', '$'], ['\\(', '\\)']]

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
