# Netlify config for AutoGPT docs

# Build settings
[build]
  publish = "public"
  command = "mkdocs build"
  environment = { NODE_ENV = "production" }

# Ignore specific files while deploying
[build.ignore]
  git-ignore = true
  file = "!docs/**"
  file = "!mkdocs.yml"
  file = "!CONTRIBUTING.md"
  file = "!CODE_OF_CONDUCT.md"
  file = "!LICENSE"
